inveniosoftware/react-invenio-forms

- src/lib/TextField.js
Turns out that the TextField had 2 layers of `<div class='field'>`
which interfered with layout in forms. Removing it allows us
to place the TextField correctly and get array rows to fill out
the length of the row.
I had to remove ErrorLabel from TextField to achieve this, but the
error props seems enough. I have attached screenshots to show it.
Needed for https://github.com/inveniosoftware/react-invenio-deposit/issues/171
> TextField: remove redundant field layer [+]

- src/lib/ArrayField.js
- the button fix is because buttons that expect **only** an icon should have `icon`, but that's not the case for the array add button. 
- required for https://github.com/inveniosoftware/react-invenio-deposit/issues/171
> ArrayComponent: add help text + fix button

- src/lib/RemoteSelectField.js
partially closes inveniosoftware/invenio-app-rdm#738
> RemoteSelectField: use 'suggest' instead of 'q'

- CHANGES.md
- package-lock.json
- package.json
- src/lib/RemoteSelectField.js
- RemoteSelectField: add preSearchChange for subjects filtering
- release: v0.8.2
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/918 in part
> RemoteSelectField: add preSearchChange

- package-lock.json
- package.json
- part of closing inveniosoftware/invenio-app-rdm#956
to be compatible with inveniosoftware/invenio-search-ui#122
- dependencies: bump axios peer dependency
- release: v0.8.5
> dependencies: bump axios peer dependency

- CHANGES.md
- package-lock.json
- package.json
- src/lib/RichInputField.js
- Also detect if label is just text or component, so no extraneous
wrapping + label becomes red if error when text OR component is passed.
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/966 in part
> richinputfield: make it require-able error-able [+]

- package.json
- src/lib/RemoteSelectField.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/810
TEMPORARY SOLUTION: To be removed when this [(axios) issue](https://github.com/axios/axios/issues/3316) is fixed.
> RemoteSelectField: Adds paramsSerializer to axios to encode brackets

- CHANGES.md
- package-lock.json
- package.json
- src/lib/ArrayField.js
- part of closing inveniosoftware/invenio-app-rdm#1146
- ArrayField: use a stable key for items:
This is a bit of a tricky one. Issue inveniosoftware/invenio-app-rdm#1146
summarizes the observed problem. The source of it was in bad interaction
between TextField, formik and list of React components. tldr; we didn't use
stable keys.
In order to keep the benefits of TextField's optimizations, I fixed the
key problem (see https://reactjs.org/docs/lists-and-keys.html#keys) by
generating artificial keys in react-invenio-deposit's deserialization
of concerned fields and by making any new item in the array
be injected with a key that will never cross those artificially generated
ones in react-invenio-deposit. This ends up giving us stable keys which in
turn makes our React list behave correctly. …
> 1146 arrayfield item deletion

- src/lib/elements/GridResponsiveSidebarColumn.js
- src/lib/elements/index.js
- Added responsive sidebar component that can be opened or closed on mobile/tablet.
- Sidebar closes on mobile/tablet when clicking the close-button and/or outside the sidebar.
- On desktop, the sidebar is always visible.
__Tablet__
__Mobile__
> elements: add responsive sidebar

- src/lib/forms/TextField.js
Hides label if there is no label-content. To avoid extra spacing in the layout.
> text-field: hide helptext label if no content

- src/lib/forms/TextField.js
Closes https://github.com/inveniosoftware/invenio-communities/issues/628
**Needs PR** https://github.com/inveniosoftware/invenio-communities/pull/636 <<-- has video recording
Changed `handleChange` to include the `onChange` function from the parent. To not have duplicates of `onChange`, this prop is removed from the `uiProps` passed to `<Form.Input/>`.
> text field: include onChange function from parent

- src/lib/elements/GridResponsiveSidebarColumn.js
The `GridResponsiveSidebarColumn` component is causing a lot of errors in the console due to conflicting width values. 
We have defined a default `width` value which is conflicting when we use the responsive width props instead (`mobile`, `tablet`, `computer`, ...).
This PR sets the default value to `undefined`.
> responsive sidebar: remove default width value

- src/lib/forms/widgets/text/MultiInput.js
- src/lib/forms/widgets/text/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1872
Adding `MultiInput` widget. A user can use this widget to insert a list of text values.
> Add multi input

- src/lib/forms/ArrayField.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2028
https://user-images.githubusercontent.com/6756943/214078633-6962f1d8-d7d1-4baf-828b-5633d9ec42eb.mov
This leas down to several important questions:
- Could we simply fall back to "If it is mandatory we always `showEmptyValue`" and we don't in the opposite case?
- Adding this "hasBeenShown", now opens the door to "enableHasBeenShown". What if the user actually wants to have it always displayed at least once?
This could derivate in an infinite loop of conditions, it should be discussed where to limit it
Thanks @jrcastro2  for the help!
> array field: show empty value only once

- src/lib/forms/widgets/text/TextArea.js
Before: default semantic-ui rows count 3 used
After: specified amount of rows used (default still 3)
closes https://github.com/inveniosoftware/invenio-banners/issues/10
> widgets: add rows props to TextArea component

- package.json
When developing the `react-invenio-forms` module with `invenio-cli assets watch-module --link /path/to/react-invenio-forms`, then the `{pre,post,}link-dist` steps will copy the `package.json` into `dist/` and modify it slightly.
Also, the `dist` directory will be linked: `${venv}/var/instance/assets/node_modules/react-invenio-forms -> /path/to/react-invenio-forms/dist`.
The directory structure should look like the following:
```
assets/node_modules/react-invenio-forms
├── cjs
│   ├── index.js
│   └── index.js.map
├── esm
│   ├── index.js
│   └── index.js.map
└── package.json
```
Without this change, the `package.json` will include the following three entries:
```
"main": "cjs/index.js",
"browser": "dist/cjs/index.js",
"module": "esm/index.js",
```
The `dist/cjs/index.js` doesn't exist …
> Fix 'browser' entry in dist/package.json

- src/lib/elements/GridResponsiveSidebarColumn.js
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/182
- Changes the sidebar element to `<aside>` and adds aria-label prop for easier screen reader navigation.
> responsive sidebar: add aria-label prop and aside wrapper elem

- CHANGES.md
- package-lock.json
- package.json
> release: v2.8.0

- CHANGES.md
- package-lock.json
- package.json
- src/lib/forms/widgets/custom_fields/ComposeFields.js
- src/lib/forms/widgets/custom_fields/CustomFields.js
- src/lib/forms/widgets/custom_fields/Extensions.js
- src/lib/forms/widgets/custom_fields/ListAndFilterCustomFields.js
- src/lib/forms/widgets/custom_fields/index.js
- src/lib/forms/widgets/loader.js
* closes https://github.com/zenodo/rdm-project/issues/649
> custom_fields: compose fields from given list

- src/lib/forms/widgets/custom_fields/CustomFields.js
- src/lib/forms/widgets/custom_fields/SubjectAutocompleteDropdown.js
- src/lib/forms/widgets/custom_fields/index.js
Closes Issue [#733](https://github.com/zenodo/zenodo-rdm/issues/733)
**Reminder**
2. You agree that you …
> custom_ fields: added subject autocomplete dropdown

- src/lib/forms/RemoteSelectField.js
The remote select field assumes that we always want to pass the `searchQuery` with `?suggest=[searchQuery]`. Often we want to instead use `q=[searchQuery]` or similar. This PR allows us to customise the name of the parameter using props
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> RemoteSelect: pass searchQueryParamName as a property

- src/lib/forms/RichEditor.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2730
* See https://www.tiny.cloud/docs/tinymce/6/react-ref/#initialvalue
* Add the missing `onEditorChange` and `initialValue` props.
* There was ambiguity between `value` and `initialValue` in the props consumption; this change also fixes that.
* I intentionally kept the prop `value={inputValue}` as `value={value}` seems to conflict with the requests package. 
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
> Editor: Fix Jumping Cursor

- CHANGES.md
- package.json
- src/lib/forms/RichInputField.js
* Added missing initialValue prop for RichInputField
* Update prop value to inputValue 
* This will fix the input text issue in deposit pages, and communities settings pages
* Request comments work as expected.
> Communities Invite members still need to be fixed
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2771
I'm currently on vacation, from a quick test when I changed `inputValue` to a function in the `RichEditor` instead of the `RichInputField`, it caused request comments to not clear the input after submission. This PR satisfies all editors except the "[community members invite](https://github.com/inveniosoftware/invenio-communities/compare/master...Samk13:invenio-communities:fix-richEditor-invitation-modal)" editor, for …
> Editor: Update RichInputField to use inputValue instead of value

- src/lib/forms/widgets/custom_fields/CustomFields.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/143
> customfields: allow hidding section name

- src/lib/api/connector.js
* closes https://github.com/zenodo/rdm-project/issues/598
> ajax: change default accept headers for all ajax calls

- src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
- src/lib/elements/contrib/invenioRDM/records/index.js
For https://github.com/inveniosoftware/invenio-rdm-records/pull/1804
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1805
Refactored code to display affiliation/name suggestions into component so it can be used everywhere we use this API
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> components: add affiliations suggestions display component

- src/lib/forms/TextField.js
- src/lib/forms/widgets/select/Dropdown.js
- src/lib/forms/widgets/text/Input.js
* closes https://github.com/inveniosoftware/invenio-jobs/issues/49
> widgets: propagate initial value field

- src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
* Fixes a display issue where the selected affiliation value is not
displayed on the form after saving/closing the creator modal.
https://github.com/user-attachments/assets/a28bdd2b-25c9-4b65-b8b7-28cbd8b128b1
> affiliations: fix display value after saving form

- package-lock.json
- package.json
- src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
- src/lib/forms/RemoteSelectField.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/193
> records: allow to override affiliations display

- src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
- src/lib/forms/RemoteSelectField.js
- src/lib/forms/widgets/custom_fields/AddDiscoverableFieldsModal.js
- Closes https://github.com/inveniosoftware/invenio-vocabularies/issues/438
- **RemoteSelectField: fix handling of multiple value selection**
- **affiliations: fix serialization values**
* Fixes a bug where dropdown values with the same title/name but
different unique identifiers would be mixed after selection and only
the first one would be actually selected for its value.
- **affiliations: render organization acronym in subheader**
> Affiliations dropdown fixes

- src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
Partially Closes: https://github.com/inveniosoftware/react-invenio-forms/issues/268
**Frontend**
**Reminder**
2. You …
> affiliations: update value property to use id

- src/lib/utils/flattenAndCategorizeErrors.js
Closes Issue https://github.com/inveniosoftware/invenio-rdm-records/issues/1980
**Frontend**
**Reminder**
2. You agree that you have the right to …
> utils: updated string error handling in flattenAndCategorizeErrors

- src/lib/forms/widgets/custom_fields/CustomFields.js
- src/lib/forms/widgets/custom_fields/DiscoverFieldsSection.js
- src/lib/forms/widgets/custom_fields/index.js
- src/lib/forms/widgets/loader.js
* allow to rename DiscoverFieldsSection label
* this PR adds functionality of defining a custom sections widget to group custom fields as we see fit
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/310
Example
> custom_fields: add support for ui section widget

- src/lib/forms/FeedbackLabel.js
* Fixes zenodo/zenodo-rdm#1135
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
> forms: FeedbackLabel: display unescaped description (sanitized HTML)

- src/lib/forms/RichEditor.js
* This is useful when the input field has a character count limit, allowing users to see the current character count.
* Related to https://github.com/inveniosoftware/invenio-requests/pull/391
* Partially closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2731
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> editor: Add word count plugin to RichEditor toolbar

- src/lib/forms/FeedbackLabel.js
Fixes inveniosoftware/invenio-rdm-records#1980
How to reproduce the problem:
1. Choose resource type journal article
2. Choose a wrong license
3. Save
4. The journal article license message appears
5. Choose resource type book
6. Save
7. The backend is sending the new book license message, but the frontend still shows the old journal article message
> forms: FeedbackLabel: fix new prop not displayed due to state usage

- .eslintrc.yml
- CHANGES.md
- package-lock.json
- package.json
- src/lib/forms/RichInputField.js
- src/lib/forms/fieldComponents.js
- src/lib/forms/index.js
- src/lib/forms/widgets/array/Array.js
- src/lib/forms/widgets/array/index.js
- src/lib/forms/widgets/select/AutocompleteDropdown.js
- src/lib/forms/widgets/select/Dropdown.js
- src/lib/forms/widgets/select/index.js
- src/lib/forms/widgets/text/BooleanCheckbox.js
- src/lib/forms/widgets/text/Input.js
- src/lib/forms/widgets/text/MultiInput.js
- src/lib/forms/widgets/text/NumberInput.js
- src/lib/forms/widgets/text/RichInput.js
- src/lib/forms/widgets/text/TextArea.js
- src/lib/forms/widgets/text/index.js
Closes https://github.com/inveniosoftware/react-invenio-forms/issues/297
---
**This is a draft proposal of a solution for this issue, please let me know if you have any suggestions on how to better implement it.**
* This commit demonstrates a potential method of implementing `Overridable` support for custom fields.
* When creating a custom field [UI definition](https://inveniordm.docs.cern.ch/customize/metadata/custom_fields/records/#upload-deposit-form), the user simply has to specify an additional `id` prop with their desired ID value for the Overridable. Then, they can specify a `parametrize` in the `overridableRegistry/mapping.js` as usual.
* The aim is to have a set of common props that can be applied to all the field widgets, similarly to …
> overridable: Implement for custom fields
