.travis.yml, src/lib/core/FieldLabel.js, src/lib/core/FieldLabel.test.js, src/lib/core/index.js
Added travis testing for the project and "tested" FieldLabel.
@lnielsen should add the deploy key in another commit + much like there is work to document pypi package deployment, there should be some similar documentation for npm packages.
=> FieldLabel: add and test

.editorconfig, README.md, src/lib/core/RadioField.js, src/lib/core/RadioField.test.js, src/lib/core/index.js
Part of https://github.com/inveniosoftware/invenio-app-rdm/issues/122
=> Add radio field (sync with RDM)

src/lib/ArrayField.js, src/lib/RadioField.js
* Show errors in ArrayField
* Simplify RadioField
=> lib: component refactoring

src/lib/AccordionField.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/466
=> accordion: use segments

CHANGES.md, package-lock.json, package.json, src/lib/ArrayField.js
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/167
=> ArrayComponent: turn buttons grey + right align

CHANGES.md, package-lock.json, package.json, src/lib/RadioField.js, src/lib/TextField.js, src/lib/ToggleField.js, src/lib/index.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/154
=> Toggle and fixes

src/lib/TextField.js
closes inveniosoftware/react-invenio-deposit/issues/186
=> TextField: helptext for input

src/lib/FieldLabel.js
(note) most top-level fields are created with this component.
closes inveniosoftware/react-invenio-deposit#88
=> FieldLabels: injecting classname for labels

src/lib/BaseForm/BaseForm.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/534
=> baseForm: remove container wrapper from children

src/lib/RichInputField.js
related to inveniosoftware/invenio-app-rdm#596
=> RichInputField: accept editorConfig and pass it as config to CKEditor

src/lib/RemoteSelectField.js
* Increases suggestion size
* partially closes https://github.com/inveniosoftware/invenio-app-rdm/issues/738
=> RemoteSelectField: extra params

src/lib/GroupField.js, src/lib/RichInputField.js, src/lib/TextField.js
* From now on TextField and RichInputField only update
formik state onBlur (instead of onChange)
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/792
=> fields: Optimize fields

src/lib/RemoteSelectField.js
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/326
=> RemoteSelectedField: expose added item serialization

src/lib/BooleanField.js, src/lib/RichInputField.js, src/lib/SelectField.js, src/lib/TextField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/965
=> fields: display initialErrors

src/lib/ErrorLabel.js
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/366
=> additional_description: fix error display

src/lib/SelectField.js
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/364
=> selectfield: reset value after onchange

.prettierrc, package-lock.json, package.json, src/demos/App.js, src/lib/forms/AccordionField.js, src/lib/forms/ActionButton.js, src/lib/forms/ArrayField.js, src/lib/forms/BooleanField.js, src/lib/forms/ErrorLabel.js, src/lib/forms/ErrorMessage.js, src/lib/forms/FieldLabel.test.js, src/lib/forms/GroupField.js, src/lib/forms/RadioField.js, src/lib/forms/RemoteSelectField.js, src/lib/forms/RichInputField.js, src/lib/forms/SelectField.js, src/lib/forms/TextAreaField.js, src/lib/forms/TextField.js, src/lib/forms/ToggleField.js
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
1. …
=> formatting: update prettier

src/lib/forms/TextField.js
* resets error onBlur to remove any previous errors in the TextField,
which is preventing submission.
* closes inveniosoftware/react-invenio-deposit#439
=> TextField: reset error onBlur

src/lib/forms/RichInputField.js
Added `UIProps` to `RichInputField`
=> rich input field: add ui props

src/lib/elements/Image.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/482
=> image: add placeholder loader

src/lib/forms/AccordionField.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/471
- Checks if any of the child fields in the accordion has errors
Related to PR https://github.com/inveniosoftware/invenio-app-rdm/pull/1487
=> accordion field: add logic for child fields errors

src/lib/forms/RemoteSelectField.js
fixed bug where item was not selected after being added by the user in the dropdown
=> remote select field: select item if added

src/lib/forms/ArrayField.js, src/lib/forms/widgets/array/Array.js
=> array: general fixes

package-lock.json, package.json
=> release: v0.10.18

src/lib/forms/RemoteSelectField.js, src/lib/forms/widgets/array/Array.js
=> global: fix proptypes

package-lock.json, package.json, src/lib/forms/widgets/text/MultiInput.js
=> MultiInput: set noresults message to placeholder prop

src/lib/api/connector.js, src/lib/api/index.js
=> Axios: Centralize imports

src/lib/forms/ArrayField.js
* closes https://github.com/zenodo/who-rdm/issues/4
=> arrayfield: add required options

CHANGES.md, package-lock.json, package.json
=> release: v1.1.2

package-lock.json, src/lib/elements/bulk_actions/SearchResultsBulkActions.js, src/lib/elements/bulk_actions/SearchResultsBulkActionsManager.js, src/lib/elements/bulk_actions/SearchResultsRowCheckbox.js, src/lib/elements/bulk_actions/context.js, src/lib/elements/bulk_actions/index.js, src/lib/elements/contrib/index.js, src/lib/elements/contrib/invenioRDM/groups/index.js, src/lib/elements/contrib/invenioRDM/index.js, src/lib/elements/contrib/invenioRDM/users/UserListItemCompact.js, src/lib/elements/contrib/invenioRDM/users/index.js, src/lib/elements/index.js
* components: add bulk action handlers
* closes https://github.com/inveniosoftware/invenio-requests/issues/347
=> components: add contrib user search list display

CHANGES.md, package-lock.json, package.json, src/lib/forms/AccordionField.js, src/lib/forms/TextField.js
* closes https://github.com/zenodo/who-rdm/issues/84
=> fields: displays initial errors

src/lib/forms/ArrayField.js, src/lib/forms/RemoteSelectField.js, src/lib/forms/SelectField.js, src/lib/forms/TextField.js, src/lib/forms/widgets/select/Dropdown.js
**Partially Fixes Issues  [#1437](https://github.com/inveniosoftware/invenio-rdm-records/issues/1437#issue-1875533280) and [#1461 ](https://github.com/inveniosoftware/invenio-rdm-records/issues/1461#issue-1892576243)related to the Accessibility of Deposit Form** 
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> Accessibility: fixed deposit form

src/lib/forms/TextAreaField.js
Partially Closes Issue [#1022](https://github.com/inveniosoftware/invenio-communities/issues/1022)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> removed duplicate Ids

src/lib/forms/RemoteSelectField.js, src/lib/forms/SelectField.js
Partially Closes Issue [#2455
](https://github.com/inveniosoftware/invenio-app-rdm/issues/2455)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> UI deposit form modals

src/lib/elements/contrib/invenioRDM/users/UserListItemCompact.js
Partially Closes Issue [#375](https://github.com/zenodo/rdm-project/issues/375)
**Reminder**
2. You …
=> user: added username as fallback

src/lib/elements/ErrorMessage.js
* closes https://github.com/zenodo/rdm-project/issues/482
=> ErrorMessage: add icon attribute only when needed

src/lib/elements/ErrorMessage.js
Related to (2201)[https://github.com/inveniosoftware/invenio-app-rdm/pull/2201] 
screenshot:
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> widget: fix error message content

src/lib/forms/RichEditor.js
Closes Issue [#308](https://github.com/zenodo/ops/issues/308)
**Reminder**
2. You agree that you have …
=> editor: disabling tinymce context menu

src/lib/forms/widgets/custom_fields/ComposeFields.js
Closes Issue [#651](https://github.com/zenodo/rdm-project/issues/651)
**Reminder**
2. You agree that you …
=> custom fields: added check for unfilled fields

CHANGES.md, package-lock.json, package.json
=> release: v3.4.0

src/lib/forms/RemoteSelectField.js, src/lib/forms/widgets/custom_fields/SubjectAutocompleteDropdown.js
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2767
=> forms: RemoteSelectField: Display initial suggestions in dropdown

src/lib/forms/RichEditor.js
Fixes #251
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …
=> editor: disable TinyMCE convert_urls to fix same domain URLs

CHANGES.md, package-lock.json, package.json
Release v4.1.0.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> release: v4.1.0

package-lock.json, package.json, src/lib/forms/widgets/custom_fields/SubjectAutocompleteDropdown.js
* closes https://github.com/inveniosoftware/react-searchkit/issues/278
=> dependencies: update axios

package-lock.json, src/lib/elements/contrib/invenioRDM/records/AffiliationsSuggestions.js
* Fixes the values required by the RemoteSelectField to be able to
display selected entries consistently.
=> affiliations: fix dropdown values

src/lib/forms/widgets/custom_fields/SubjectAutocompleteDropdown.js
Fixes the issue of subjects with same name not appearing in  the dropdown.
**Frontend**
**Reminder**
2. You agree that …
=> subjects: updated subject serialization

src/lib/forms/widgets/custom_fields/AddDiscoverableFieldsModal.js
* closes CERNDocumentServer/cds-rdm#350
=> custom-fields: replace Cancel with Close btn in modal

src/lib/forms/AccordionField.js, src/lib/forms/FeedbackLabel.js, src/lib/forms/TextField.js
Fixes inveniosoftware/invenio-rdm-records#1991
=> forms: show icon and tooltip for new error format with severity error

package-lock.json, package.json, src/lib/forms/widgets/custom_fields/ListAndFilterCustomFields.js, src/lib/forms/widgets/text/BooleanCheckbox.js
Target some of the vuln listed here: https://github.com/inveniosoftware/react-invenio-forms/security/dependabot?q=is%3Aopen+sort%3Amost-important
**Frontend**
**Reminder**
1. You license your …
=> chore: update dependencies

CHANGES.md, package-lock.json, package.json
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> chore: relock deps and update babel-runtime and axios

.github/workflows/npm-publish.yml, CHANGES.md
* see: https://github.com/inveniosoftware/workflows/issues/2
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
=> Fix-publish-workflow

src/lib/forms/AccordionField.js, src/lib/forms/FeedbackLabel.js
=> feedback label: fix nested errors display

src/lib/forms/AccordionField.js, src/lib/forms/FeedbackLabel.js, src/lib/forms/widgets/custom_fields/CustomFields.js
* correct accordion labels for deeply nested errors
* add missing pointing values
* UI: Use severityChecks label instead severity key
* fix: pass severityChecks to CustomFields
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> Checks bug fixes

src/lib/forms/RemoteSelectField.js
fixes: https://github.com/inveniosoftware/invenio-vocabularies/issues/499
=> RemoteSelectField: Show default search results after selection/addition
